export const postCards = {
  // javascript: [
  tutorials: [
    {
      title: "Tutorials Lodash Fundamentals",
      image: "/picture1.png",
      description: `This is a short post description. 
        This is a short post description. 
        This is a short post description`,
      tags: ["javascript", "array"],
      createdAt: "Jan 21, 2021",
      category: "tutorials",
    },
    {
      title: "TutorialsLodash Fundamentals",
      image: "/picture1.png",
      description: `This is a short post description. 
        This is a short post description. 
        This is a short post description. 
        This is a short post description
        This is a short post description`,
      tags: ["javascript", "variable", "node.js"],
      createdAt: "Jan 21, 2021",
      category: "tutorials",
    },
    {
      title: "Tutorials Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["browser", "lodash", "variable"],
      createdAt: "Jan 21, 2021",
      category: "tutorials",
    },
    {
      title: "Tutorials Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["async", "react", "promise"],
      category: "tutorials",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Tutorials Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash", "promise"],
      category: "tutorials",
      createdAt: "Jan 21, 2021",
    },
  ],

  algorithms: [
    {
      title: "Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash", "react"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "async"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
    // ],
    // algorithms: [
    {
      title: "Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["algorithm", "O-notation"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["list", "linkedList"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["graph", "cycle", "algorithm"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["binary-tree", "tree", "algorithm"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "algorithm"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
    // ],
    // uncategorized: [
    {
      title: "Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "algorithms",
      createdAt: "Jan 21, 2021",
    },
  ],

  engineering: [
    {
      title: "Engineering Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Engineering Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "Jan 21, 2021",
    },
    {
      title: "Engineering: JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "November 21, 2021",
    },
    {
      title: "Engineering JavaScript Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "October 19, 2021",
    },
    {
      title: "Engineering: JavaScript Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "June 30, 2021",
    },
    {
      title: "Engineering: JavaScript Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "July 21, 2021",
    },
    {
      title: "Engineering: JavaScript Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "July 19, 2021",
    },
    {
      title: "Engineering JavaScript Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "July 30, 2021",
    },
    {
      title: "Engineering: Algorithms Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "January 21, 2019",
    },
    {
      title: "Engineering: Algorithms Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "April 03, 2021",
    },
    {
      title: "Engineering: Algorithms Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "September 21, 2019",
    },
    {
      title: "Engineering: Uncategorized Lodash Fundamentals",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "March 21, 2019",
    },
    {
      title: "Engineering Introduced Uncategorized Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "December 01, 2021",
    },
    {
      title: "Engineering: Uncategorized Lodash Advanced Concepts",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "March 15, 2019",
    },
    {
      title: "Engineering: Uncategorized Lodash Examples",
      image: "/picture1.png",
      description: "This is a short post description",
      tags: ["javascript", "lodash"],
      category: "engineering",
      createdAt: "May 21, 2021",
    },
    {
      title: "Engineering interface in Java",
      image: "/picture1.png",
      description: "What you should know about Comparable Interface in Java",
      tags: ["java", "interface", "comparable", "compareTo"],
      category: "engineering",
      createdAt: "May 21, 2021",
    },
  ],
};
export const categories = ["javascript", "algorithms", "uncategorized"];

